### ISSUE TITLE
Adding like feature

### ISSUE THREAD

**Issue by tdivyanshu99** [tpriyanshu90/facebook-clone#4]
Currently, there is no Like Post functionality. I want to add this functionality so that users are able to like the posts. It will also, increase the engagement of the users with the posts.

In the first image, the like button is non-functional.
In the second image, it is my proposed solution, where the like button is made functional.

![Add a subheading (1)](https://github.com/tpriyanshu90/facebook-clone/assets/55032303/f9da73d8-52c4-414a-8078-ead2df0feea1)

**Comment by tpriyanshu90** [comment]
Hi Divyanshu, this feature looks like a must have feature. Assigning the issue to you to work on this.
